export enum FILTERBY {
  ALL = "ALL",
  TIME_TRIGGER_RULES = "TIME_TRIGGER_RULES",
  MACHINE_STOP_RULES = "MACHINE_STOP_RULES",
  CREATE_BY_ME = "CREATE_BY_ME",
  NOT_CREATE_BY_ME = "NOT_CREATE_BY_ME",
  DEVIATION_PARAMETER = "DEVIATION_PARAMETER",
  SPC_PARAMETER = "SPC_PARAMETER",
}

export enum SORTBY {
  DATE_CREATED = "DATE_CREATED",
  ALPHABET = "ALPHABET",
  ACTIVE_FIRST = "ACTIVE_FIRST",
  LAST_FIRED = "LAST_FIRED",
}

export enum SORTBY_TYPE {
  ASC = "ASC",
  DES = "DES",
}
